### ISSUE TITLE
Calculation module multiply is using lots of memory upon running its test

### ISSUE THREAD

**Issue by knackbord** [enermaps/enermaps#122]
I don't have enough RAM:

```
PS C:\Users\jakob.rager\Documents\Programming\enermaps> docker-compose up --build
Building cm-multiply
Step 1/8 : FROM ubuntu:20.04
 ---> f643c72bc252
Step 2/8 : RUN apt-get update &&     apt-get --yes install python3 python3-pip &&    rm -rf /var/cache/apt/archives/
 ---> Using cache
 ---> 84371f2f0d02
Step 3/8 : WORKDIR cm-multiply
 ---> Using cache
 ---> dbad8093ab1a
Step 4/8 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> 575d64ae9925
Step 5/8 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> 787b8b0533c9
Step 6/8 : COPY . .
 ---> Using cache
 ---> 06d10fa4f609
Step 7/8 : RUN python3 test.py
 ---> Running in ce4ffb6db32d
..E
======================================================================
ERROR: test_zonal_stats_switzerlandbbox (__main__.TestCM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 67, in test_zonal_stats_switzerlandbbox
    stats = rasterstats(selection, raster, 1)
  File "/cm-multiply/multiply_raster.py", line 47, in rasterstats
    stats = zonal_stats(
  File "/usr/local/lib/python3.8/dist-packages/rasterstats/main.py", line 31, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/rasterstats/main.py", line 220, in gen_zonal_stats
    feature_stats['min'] = float(masked.min())
  File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 5700, in min
    result = self.filled(fill_value).min(
  File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 3793, in filled
    result = self._data.copy('K')
MemoryError: Unable to allocate 2.85 GiB for an array with shape (22114, 34551) and data type float32

----------------------------------------------------------------------
Ran 3 tests in 81.826s

FAILED (errors=1)
ERROR: Service 'cm-multiply' failed to build : The command '/bin/sh -c python3 test.py' returned a non-zero code: 1
```

**Comment by gcmalloc** [comment]
Raster is  39.5 KB on disk (https://github.com/enermaps/enermaps/blob/master/cm/multiply/testdata/GeoTIFF_test.tif), the problem is actually covered by https://github.com/perrygeo/python-rasterstats/issues/227. rasterstat will by default allocate a array  covering the size of the feature, regardless of the size of the underlying raster. fix was implemented in https://github.com/perrygeo/python-rasterstats/pull/228, around 15 days ago. A new version of the library has not been yet released, I will wait for this and update the rasterstat library.

As a more general rule of thumb, we can set the memory limit of the cm using the docker-compose.yml option, it would look like:


```yaml
        limits:
          memory: 4G
        reservations:
          memory: 2G
```

Currently, no hard limit or thought about cpu limits.
