### ISSUE TITLE
Rasterio cannot find gcs.csv

### ISSUE THREAD

**Issue by gperonato** [enermaps/enermaps#166]
I got this when building the multiply CM. It looks like an [issue](https://github.com/mapbox/rasterio/issues/1539) due to the installation from PyPi

```
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
..E
======================================================================
ERROR: test_zonal_stats_switzerlandbbox (__main__.TestCM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 65, in test_zonal_stats_switzerlandbbox
    stats = rasterstats(selection, raster, 1)
  File "/cm-multiply/multiply_raster.py", line 76, in rasterstats
    project = pyproj.Transformer.from_crs(
  File "/usr/local/lib/python3.8/dist-packages/pyproj/transformer.py", line 368, in from_crs
    _Transformer.from_crs(
  File "pyproj/_transformer.pyx", line 349, in pyproj._transformer._Transformer.from_crs
pyproj.exceptions.ProjError: Error creating Transformer from CRS.
```

**Comment by gperonato** [comment]
@cedricserugendo can you please check if you manage to build the multiply CM?

**Comment by dianevg** [comment]
Ca fonctionne chez moi sur Windows. Désolé ça aide pas tant :-/. Une idée: Pour l'instant on ne spécifie pas la version de rasterio que l'on utilise dans le fichier requirements.txt. Il serait possible qu'on utilise des versions différentes ? On peut peut-être réessayé en spécifiant la version de rasterio demandée.

**Comment by cedricserugendo** [comment]
the bug is fixed in the `new_cm` branch
