### ISSUE TITLE
Build error on Win 10 with docker

### ISSUE THREAD

**Issue by knackbord** [enermaps/enermaps#476]
[+] Building 18.1s (112/120)
 => [enermaps_cm-multiply internal] load build definition from Dockerfile                                                       0.2s
 => => transferring dockerfile: 32B                                                                                             0.0s
 => [enermaps_cm-heatlearn internal] load build definition from Dockerfile                                                      0.1s
 => => transferring dockerfile: 735B                                                                                            0.0s
 => [enermaps_cm-heat-demand internal] load build definition from Dockerfile                                                    0.4s
 => => transferring dockerfile: 665B                                                                                            0.1s
 => [enermaps_frontend internal] load build definition from Dockerfile                                                          0.5s
 => => transferring dockerfile: 32B                                                                                             0.1s
 => [enermaps_cm-hdd_cdd internal] load build definition from Dockerfile                                                        0.6s
 => => transferring dockerfile: 32B                                                                                             0.1s
 => [enermaps_cm-dhexppot internal] load build definition from Dockerfile                                                       0.8s
 => => transferring dockerfile: 726B                                                                                            0.1s
 => [enermaps_cm-buildingload internal] load build definition from Dockerfile                                                   0.9s
 => => transferring dockerfile: 443B                                                                                            0.1s
 => [enermaps_api internal] load build definition from Dockerfile                                                               0.6s
 => => transferring dockerfile: 32B                                                                                             0.1s
 => [enermaps_cm-empty internal] load build definition from Dockerfile                                                          2.2s
 => => transferring dockerfile: 32B                                                                                             0.0s
 => [enermaps_cm-refurbish internal] load build definition from Dockerfile                                                      2.4s
 => => transferring dockerfile: 3.08kB                                                                                          0.1s
 => [enermaps_cm-multiply internal] load .dockerignore                                                                          0.8s
 => => transferring context: 2B                                                                                                 0.1s
 => [enermaps_cm-heatlearn internal] load .dockerignore                                                                         0.9s
 => => transferring context: 2B                                                                                                 0.1s
 => [enermaps_cm-heat-demand internal] load .dockerignore                                                                       1.3s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_frontend internal] load .dockerignore                                                                             1.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-hdd_cdd internal] load .dockerignore                                                                           2.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-dhexppot internal] load .dockerignore                                                                          1.7s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-buildingload internal] load .dockerignore                                                                      1.3s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_api internal] load .dockerignore                                                                                  0.9s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-empty internal] load .dockerignore                                                                             2.1s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-refurbish internal] load .dockerignore                                                                         2.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [enermaps_cm-buildingload internal] load metadata for docker.io/library/ubuntu:20.04                                        1.9s
 => [enermaps_frontend internal] load metadata for docker.io/library/caddy:2.1.1-alpine                                         2.4s
 => [enermaps_frontend internal] load metadata for docker.io/mhart/alpine-node:12                                               2.4s
 => [enermaps_cm-heatlearn  1/12] FROM docker.io/library/ubuntu:20.04@sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573  0.0s
 => [enermaps_cm-dhexppot internal] load build context                                                                          1.3s
 => => transferring context: 6.85kB                                                                                             0.2s
 => [enermaps_cm-refurbish internal] load build context                                                                         1.4s
 => => transferring context: 4.57kB                                                                                             0.1s
 => [enermaps_frontend stage-1 1/4] FROM docker.io/library/caddy:2.1.1-alpine@sha256:77af551bbc1d8b3e4f6821f1958f4fef568e4f21e  0.0s
 => [enermaps_cm-heat-demand internal] load build context                                                                       1.5s
 => => transferring context: 5.34kB                                                                                             0.2s
 => [enermaps_api internal] load build context                                                                                  1.0s
 => => transferring context: 2.48kB                                                                                             0.2s
 => [enermaps_cm-empty internal] load build context                                                                             1.6s
 => => transferring context: 4.58kB                                                                                             0.1s
 => [enermaps_cm-multiply internal] load build context                                                                          1.7s
 => => transferring context: 9.69MB                                                                                             0.7s
 => [enermaps_cm-heatlearn internal] load build context                                                                         1.2s
 => => transferring context: 5.92kB                                                                                             0.2s
 => [enermaps_frontend internal] load build context                                                                             1.1s
 => => transferring context: 2.93kB                                                                                             0.2s
 => [enermaps_cm-buildingload internal] load build context                                                                      1.2s
 => => transferring context: 5.20kB                                                                                             0.2s
 => [enermaps_cm-hdd_cdd internal] load build context                                                                           1.6s
 => => transferring context: 4.58kB                                                                                             0.2s
 => [enermaps_frontend stage-0 1/6] FROM docker.io/mhart/alpine-node:12@sha256:554727decbab367c7436b33da9635c039d64fb1940e48e8  0.0s
 => CACHED [enermaps_cm-hdd_cdd  2/12] RUN ln -snf /usr/share/zoneinfo/Europe/Zurich /etc/localtime && echo Europe/Zurich > /e  0.0s
 => CACHED [enermaps_api 3/8] RUN apt-get update &&     apt-get install --yes         python3-mapnik         python3-pip        0.0s
 => CACHED [enermaps_api 4/8] WORKDIR /api                                                                                      0.0s
 => CACHED [enermaps_api 5/8] COPY requirements.txt requirements.txt                                                            0.0s
 => CACHED [enermaps_api 6/8] RUN pip3 install -r requirements.txt                                                              0.0s
 => CACHED [enermaps_api 7/8] COPY . .                                                                                          0.0s
 => CACHED [enermaps_cm-dhexppot  3/11] RUN chmod 1777 /tmp &&     apt-get update &&     apt-get --yes install python3 python3  0.0s
 => CACHED [enermaps_cm-dhexppot  4/11] WORKDIR cm-dhexppot                                                                     0.0s
 => CACHED [enermaps_cm-dhexppot  5/11] RUN mkdir -p tmp                                                                        0.0s
 => CACHED [enermaps_cm-dhexppot  6/11] COPY cm_dhexppot/requirements.txt requirements.txt                                      0.0s
 => CACHED [enermaps_cm-dhexppot  7/11] RUN pip3 install -r requirements.txt                                                    0.0s
 => CACHED [enermaps_cm-dhexppot  8/11] COPY base /tmp/base                                                                     0.0s
 => CACHED [enermaps_cm-dhexppot  9/11] RUN cd /tmp/base && pip3 install . && python3 test.py                                   0.0s
 => CACHED [enermaps_cm-dhexppot 10/11] COPY cm_dhexppot .                                                                      0.0s
 => CACHED [enermaps_cm-refurbish  3/12] RUN apt-get update     && apt-get --yes install     git     python3     python3-pip    0.0s
 => CACHED [enermaps_cm-refurbish  4/12] RUN echo "/cm_input: /cm_inputs"     && echo "data repository: /cm_inputs/hdd-cdd/hdd  0.0s
 => CACHED [enermaps_cm-refurbish  5/12] WORKDIR refurbish                                                                      0.0s
 => CACHED [enermaps_cm-refurbish  6/12] COPY refurbish .                                                                       0.0s
 => CACHED [enermaps_cm-refurbish  7/12] RUN pip3 install -r requirements.txt                                                   0.0s
 => CACHED [enermaps_cm-refurbish  8/12] COPY base /tmp/base                                                                    0.0s
 => CACHED [enermaps_cm-buildingload 2/9] RUN apt-get update &&     apt-get --yes install python3 python3-pip &&    rm -rf /va  0.0s
 => CACHED [enermaps_cm-buildingload 3/9] COPY cm/cm_buildingload/requirements.txt requirements.txt                             0.0s
 => CACHED [enermaps_cm-buildingload 4/9] RUN pip3 install -r requirements.txt                                                  0.0s
 => CACHED [enermaps_cm-buildingload 5/9] COPY cm/base /tmp/base                                                                0.0s
 => CACHED [enermaps_cm-buildingload 6/9] RUN cd /tmp/base && pip3 install . && python3 test.py                                 0.0s
 => CACHED [enermaps_cm-buildingload 7/9] COPY cm/cm_buildingload .                                                             0.0s
 => CACHED [enermaps_cm-buildingload 8/9] RUN mkdir -p tmp                                                                      0.0s
 => CACHED [enermaps_cm-buildingload 9/9] RUN python3 test.py                                                                   0.0s
 => CACHED [enermaps_cm-heatlearn  3/10] RUN apt-get update &&     apt-get --yes install         python3         python3-pip    0.0s
 => CACHED [enermaps_cm-heatlearn  4/10] COPY cm/heatlearn/requirements.txt requirements.txt                                    0.0s
 => CACHED [enermaps_frontend stage-1 2/4] COPY Caddyfile /etc/caddy/Caddyfile                                                  0.0s
 => CACHED [enermaps_frontend stage-0 2/6] WORKDIR /app                                                                         0.0s
 => CACHED [enermaps_frontend stage-0 3/6] COPY src/package.json src/package-lock.json ./                                       0.0s
 => CACHED [enermaps_frontend stage-0 4/6] RUN npm install                                                                      0.0s
 => CACHED [enermaps_frontend stage-0 5/6] COPY src/ .                                                                          0.0s
 => CACHED [enermaps_frontend stage-0 6/6] RUN npm run build                                                                    0.0s
 => CACHED [enermaps_frontend stage-1 3/4] COPY --from=0 /app/public /frontend                                                  0.0s
 => CACHED [enermaps_frontend stage-1 4/4] WORKDIR /frontend                                                                    0.0s
 => CACHED [enermaps_cm-multiply  3/10] RUN apt-get update &&     apt-get --yes install         python3         python3-pip     0.0s
 => CACHED [enermaps_cm-empty  4/10] WORKDIR example-empty                                                                      0.0s
 => CACHED [enermaps_cm-empty  5/10] COPY example_empty/requirements.txt requirements.txt                                       0.0s
 => CACHED [enermaps_cm-empty  6/10] RUN pip3 install -r requirements.txt                                                       0.0s
 => CACHED [enermaps_cm-empty  7/10] COPY base /tmp/base                                                                        0.0s
 => CACHED [enermaps_cm-empty  8/10] RUN cd /tmp/base && pip3 install . && python3 test.py                                      0.0s
 => CACHED [enermaps_cm-empty  9/10] COPY example_empty .                                                                       0.0s
 => CACHED [enermaps_cm-empty 10/10] RUN python3 test.py                                                                        0.0s
 => [enermaps_cm-hdd_cdd] exporting to image                                                                                    2.2s
 => => exporting layers                                                                                                         0.0s
 => => writing image sha256:384f83e39c77ebf3ab708aff216412819496cb1c865377a652933a6a6fd6992f                                    0.0s
 => => naming to docker.io/library/enermaps_cm-empty                                                                            0.0s
 => => writing image sha256:16449e54abda36e02ce9f49e32b78fbc7b0479caf2ff52c1e98ad2c684dd4b19                                    0.1s
 => => naming to docker.io/library/enermaps_frontend                                                                            0.0s
 => => writing image sha256:39d034657cec3131312ac60cea5cf5005efb5f6b2a61d602294f6a10e8108e54                                    0.0s
 => => naming to docker.io/library/enermaps_cm-buildingload                                                                     0.0s
 => => writing image sha256:96adf9bfce1006a1b88fb5bbbfae9c3b8673380bbe9586a9052495d4d97decad                                    0.1s
 => => naming to docker.io/library/enermaps_cm-multiply                                                                         0.0s
 => => writing image sha256:1ddbce83a6ea0e7e11a2a6e6c48fcf6032de991688d9532fdead4627f7d7b5c7                                    0.0s
 => => writing image sha256:27a9a46eee87cddfc75bd55c432d14cd63c7ed81cecf126c15a17ce52afa9fcb                                    0.1s
 => => naming to docker.io/library/enermaps_cm-heat-demand                                                                      0.0s
 => => naming to docker.io/library/enermaps_cm-hdd_cdd                                                                          0.0s
 => CACHED [enermaps_cm-heat-demand  3/10] RUN apt-get update &&     apt-get install --yes         python3         python3-pip  0.0s
 => CACHED [enermaps_cm-heat-demand  4/10] WORKDIR cm-heat-demand                                                               0.0s
 => CACHED [enermaps_cm-heat-demand  5/10] COPY cm_heat_demand/requirements.txt requirements.txt                                0.0s
 => CACHED [enermaps_cm-heat-demand  6/10] RUN pip3 install -r requirements.txt                                                 0.0s
 => CACHED [enermaps_cm-heat-demand  7/10] COPY base /tmp/base                                                                  0.0s
 => CACHED [enermaps_cm-heat-demand  8/10] RUN cd /tmp/base && pip3 install . && python3 test.py                                0.0s
 => CACHED [enermaps_cm-heat-demand  9/10] COPY cm_heat_demand .                                                                0.0s
 => CACHED [enermaps_cm-heat-demand 10/10] RUN python3 test.py                                                                  0.1s
 => CACHED [enermaps_cm-multiply  4/10] WORKDIR cm-multiply                                                                     0.0s
 => CACHED [enermaps_cm-multiply  5/10] COPY example_multiply/requirements.txt requirements.txt                                 0.0s
 => CACHED [enermaps_cm-multiply  6/10] RUN pip3 install -r requirements.txt                                                    0.0s
 => CACHED [enermaps_cm-multiply  7/10] COPY base /tmp/base                                                                     0.0s
 => CACHED [enermaps_cm-multiply  8/10] RUN cd /tmp/base && pip3 install . && python3 test.py                                   0.0s
 => CACHED [enermaps_cm-multiply  9/10] COPY example_multiply .                                                                 0.0s
 => CACHED [enermaps_cm-multiply 10/10] RUN python3 test.py                                                                     0.0s
 => CANCELED [enermaps_cm-dhexppot 11/11] RUN python3 test.py                                                                  11.1s
 => CACHED [enermaps_cm-hdd_cdd  3/12] RUN apt-get update     && apt-get --yes install     python3     python3-pip     libgdal  0.0s
 => CACHED [enermaps_cm-hdd_cdd  4/12] RUN echo "/cm_input: /cm_inputs"     && echo "data repository: /cm_inputs/hdd-cdd/hdd-c  0.0s
 => CACHED [enermaps_cm-hdd_cdd  5/12] WORKDIR hdd_cdd                                                                          0.0s
 => CACHED [enermaps_cm-hdd_cdd  6/12] COPY hdd_cdd .                                                                           0.0s
 => CACHED [enermaps_cm-hdd_cdd  7/12] RUN pip3 install -r requirements.txt                                                     0.0s
 => CACHED [enermaps_cm-hdd_cdd  8/12] COPY base /tmp/base                                                                      0.0s
 => CACHED [enermaps_cm-hdd_cdd  9/12] RUN echo "-----\nInstalling BaseCM"     && cd /tmp/base && python3 setup.py install      0.0s
 => CACHED [enermaps_cm-hdd_cdd 10/12] RUN python3 download.py                                                                  0.0s
 => CACHED [enermaps_cm-hdd_cdd 11/12] RUN python3 schema.py                                                                    0.0s
 => CACHED [enermaps_cm-hdd_cdd 12/12] RUN python3 test.py                                                                      0.0s
 => CANCELED [enermaps_cm-heatlearn  5/10] RUN pip3 install -r requirements.txt                                                10.8s
 => ERROR [enermaps_api 8/8] RUN python3 test.py                                                                               10.4s
 => CANCELED [enermaps_cm-refurbish  9/12] RUN echo "-----\nInstalling BaseCM"     && cd /tmp/base && pip3 install .     && p  11.2s
------
 > [enermaps_api 8/8] RUN python3 test.py:
#62 9.993 Traceback (most recent call last):
#62 9.993   File "test.py", line 11, in <module>
#62 9.993     import app  # NOQA
#62 9.993   File "/api/app/__init__.py", line 11, in <module>
#62 9.993     from app.commands import cache
#62 9.993   File "/api/app/commands/cache.py", line 9, in <module>
#62 9.993     from app.common import client
#62 9.993   File "/api/app/common/client.py", line 12, in <module>
#62 9.993     from app.common import datasets, path
#62 9.993   File "/api/app/common/datasets.py", line 3, in <module>
#62 9.993     from app.models import storage
#62 9.993   File "/api/app/models/storage.py", line 7, in <module>
#62 9.993     from flask import current_app, safe_join
#62 9.993 ImportError: cannot import name 'safe_join' from 'flask' (/usr/local/lib/python3.8/dist-packages/flask/__init__.py)
------
failed to solve: executor failed running [/bin/sh -c python3 test.py]: exit code: 1

**Comment by knackbord** [comment]
Any ideas why?

**Comment by knackbord** [comment]
works now since integration of PRs
